### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KeyAs99** [alex9849/arm-shopbridge#8]
I get this error when the plugin tries to delete a shop.
I am using Quickshop: https://www.spigotmc.org/resources/quickshop-reremake-1-17-ready-multi-currency.62575/

[23:06:18 ERROR]: Could not pass event UnsellRegionEvent to ArmShopBridge v1.2.5
java.lang.NoSuchMethodError: 'java.util.Map org.maxgamer.quickshop.api.ShopAPI.getShop(org.bukkit.Chunk)'
        at net.alex9849.armshopbridge.adapters.QuickShop4Adapter.deleteShops(QuickShop4Adapter.java:35) ~[?:?]
        at net.alex9849.armshopbridge.listener.UnsellRegionListener.handleRegionReset(UnsellRegionListener.java:17) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor845.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Airplane-2]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Airplane-2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Airplane-2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.alex9849.arm.regions.Region.unsell(Region.java:1101) ~[?:?]
        at net.alex9849.arm.regions.CountdownRegion.unsell(CountdownRegion.java:125) ~[?:?]
        at net.alex9849.arm.commands.DeleteCommand.runCommandLogic(DeleteCommand.java:37) ~[?:?]
        at net.alex9849.arm.commands.BasicArmCommand.runCommand(BasicArmCommand.java:84) ~[?:?]
        at net.alex9849.arm.handler.CommandHandler.executeCommand(CommandHandler.java:51) ~[?:?]
        at net.alex9849.arm.AdvancedRegionMarket.onCommand(AdvancedRegionMarket.java:828) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Airplane-2]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Airplane-2]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2315) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2130) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2083) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1308) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1152) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Airplane-2]

**Comment by alex9849** [comment]
Ok. Looks like the plugin got incompatible with quickshop and needs an update. I'll do that within the next days. :)

**Comment by alex9849** [comment]
I wrote with the author of QuickShop. The next release of QuickShop will support ARM natively. That means you can uninstall the shopBridge :)
